# Generated by Django 4.2.1 on 2023-05-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('value', models.PositiveIntegerField()),
                ('time', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('P', 'تعریف شده'), ('A', 'واگذار شده'), ('D', 'انجام شده')], default='P', max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('assigned_contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.contractor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.employer')),
            ],
        ),
    ]
